services:
  - type: web
    name: BREATHEWISE_AQI_PREDICTOR
    env: python
    plan: free
    build:
      buildCommand: "pip install -r requirements.txt"
      pythonVersion: 3.12.3
    startCommand: "streamlit run app.py --server.port=10000 --server.enableCORS=false"
