services:
  - type: web
    name: BREATHEWISE_AQI_PREDICTOR
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=10000 --server.enableCORS=false"
    pythonVersion: 3.12.3
    region: oregon
    plan: free
